baseURL = 'https://example.org/'
languageCode = 'fi'
theme = 'proefit'
timeZone = 'Europe/Helsinki'
pluralizeListTitles = 'false'
# canonifyURLs = true
# baseUrl = 'https://jawcraig.github.io/proefit.fi/public/'
title = 'PROEFIT'
